version: '3'
services:

  polkadot:
    image: parity/polkadot:v0.8.24
    volumes:
      - "polkadot-data:/data"
    command: --rpc-external --prometheus-external --log error --rpc-cors=all

  vedran:
    command: start --fee=0.1 --auth-secret=test-secret --log-level debug
    image: nodefactory/vedran:v0.1.1
    container_name: "vedran"

  vedran-daemon:
    image: nodefactory/vedran-daemon:v0.1.2
    depends_on:
      - vedran
      - polkadot
    command: --id test-id --lb http://vedran:4000 --node-rpc http://polkadot:9933 --node-metrics http://polkadot:9615 --payout-address 0xtestaddress --log-level error

volumes:
  polkadot-data:
