version: '3'
services:

  polkadot:
    ports:
      - "127.0.0.1:30333:30333/tcp"
      - "127.0.0.1:9933:9933/tcp"
      - "127.0.0.1:9615:9615/tcp"
    image: chevdor/polkadot:latest
    volumes:
      - "polkadot-data:/data"
    command: sh -c "polkadot --rpc-external --prometheus-external --log error --rpc-cors=all"

  vedran:
    command: start --fee=0.1 --auth-secret=test-secret --log-level debug
    image: nodefactory/vedran:v0.1.0
    container_name: "vedran"

  vedran-daemon:
    image: nodefactory/vedran-daemon:v0.1.1
    depends_on:
      - vedran
      - polkadot
    entrypoint: /bin/sh -c "sleep 5; ./vedran-daemon --id test-id --lb http://vedran:4000 --node-rpc http://polkadot:9933 --node-metrics http://polkadot:9615 --payout-address 0xtestaddress --log-level error"

volumes:
  polkadot-data:
