// Code generated by mockery v2.2.1. DO NOT EDIT.

package mocks

import (
	models "github.com/NodeFactoryIo/vedran/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// RecordRepository is an autogenerated mock type for the RecordRepository type
type RecordRepository struct {
	mock.Mock
}

// Save provides a mock function with given fields: record
func (_m *RecordRepository) Save(record *models.Record) error {
	ret := _m.Called(record)

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Record) error); ok {
		r0 = rf(record)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
