// Code generated by mockery v2.2.1. DO NOT EDIT.

package mocks

import (
	models "github.com/NodeFactoryIo/vedran/internal/models"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// DowntimeRepository is an autogenerated mock type for the DowntimeRepository type
type DowntimeRepository struct {
	mock.Mock
}

// FindDowntimesInsideInterval provides a mock function with given fields: nodeID, from, to
func (_m *DowntimeRepository) FindDowntimesInsideInterval(nodeID string, from time.Time, to time.Time) ([]models.Downtime, error) {
	ret := _m.Called(nodeID, from, to)

	var r0 []models.Downtime
	if rf, ok := ret.Get(0).(func(string, time.Time, time.Time) []models.Downtime); ok {
		r0 = rf(nodeID, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Downtime)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, time.Time, time.Time) error); ok {
		r1 = rf(nodeID, from, to)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: downtime
func (_m *DowntimeRepository) Save(downtime *models.Downtime) error {
	ret := _m.Called(downtime)

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Downtime) error); ok {
		r0 = rf(downtime)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
