// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import models "github.com/NodeFactoryIo/vedran/internal/models"

// DowntimeRepository is an autogenerated mock type for the DowntimeRepository type
type DowntimeRepository struct {
	mock.Mock
}

// Save provides a mock function with given fields: downtime
func (_m *DowntimeRepository) Save(downtime *models.Downtime) error {
	ret := _m.Called(downtime)

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Downtime) error); ok {
		r0 = rf(downtime)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
