// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import models "github.com/NodeFactoryIo/vedran/internal/models"

// FeeRepository is an autogenerated mock type for the FeeRepository type
type FeeRepository struct {
	mock.Mock
}

// GetAllFees provides a mock function with given fields:
func (_m *FeeRepository) GetAllFees() (*[]models.Fee, error) {
	ret := _m.Called()

	var r0 *[]models.Fee
	if rf, ok := ret.Get(0).(func() *[]models.Fee); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]models.Fee)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RecordNewFee provides a mock function with given fields: nodeID, newFee
func (_m *FeeRepository) RecordNewFee(nodeID string, newFee int64) error {
	ret := _m.Called(nodeID, newFee)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, int64) error); ok {
		r0 = rf(nodeID, newFee)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
