// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// FeeRepository is an autogenerated mock type for the FeeRepository type
type FeeRepository struct {
	mock.Mock
}

// RecordNewFee provides a mock function with given fields: nodeID, newFee
func (_m *FeeRepository) RecordNewFee(nodeID string, newFee int64) error {
	ret := _m.Called(nodeID, newFee)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, int64) error); ok {
		r0 = rf(nodeID, newFee)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
