// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import models "github.com/NodeFactoryIo/vedran/internal/models"

// PaymentRepository is an autogenerated mock type for the PaymentRepository type
type PaymentRepository struct {
	mock.Mock
}

// Save provides a mock function with given fields: payment
func (_m *PaymentRepository) Save(payment *models.Payment) error {
	ret := _m.Called(payment)

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Payment) error); ok {
		r0 = rf(payment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
