// Code generated by mockery v2.2.1. DO NOT EDIT.

package mocks

import (
	models "github.com/NodeFactoryIo/vedran/internal/models"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// PingRepository is an autogenerated mock type for the PingRepository type
type PingRepository struct {
	mock.Mock
}

// CalculateDowntime provides a mock function with given fields: nodeId, pingTime
func (_m *PingRepository) CalculateDowntime(nodeId string, pingTime time.Time) (time.Time, time.Duration, error) {
	ret := _m.Called(nodeId, pingTime)

	var r0 time.Time
	if rf, ok := ret.Get(0).(func(string, time.Time) time.Time); ok {
		r0 = rf(nodeId, pingTime)
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	var r1 time.Duration
	if rf, ok := ret.Get(1).(func(string, time.Time) time.Duration); ok {
		r1 = rf(nodeId, pingTime)
	} else {
		r1 = ret.Get(1).(time.Duration)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(string, time.Time) error); ok {
		r2 = rf(nodeId, pingTime)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// FindByNodeID provides a mock function with given fields: nodeId
func (_m *PingRepository) FindByNodeID(nodeId string) (*models.Ping, error) {
	ret := _m.Called(nodeId)

	var r0 *models.Ping
	if rf, ok := ret.Get(0).(func(string) *models.Ping); ok {
		r0 = rf(nodeId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Ping)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(nodeId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAll provides a mock function with given fields:
func (_m *PingRepository) GetAll() (*[]models.Ping, error) {
	ret := _m.Called()

	var r0 *[]models.Ping
	if rf, ok := ret.Get(0).(func() *[]models.Ping); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]models.Ping)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ResetAllPings provides a mock function with given fields:
func (_m *PingRepository) ResetAllPings() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Save provides a mock function with given fields: ping
func (_m *PingRepository) Save(ping *models.Ping) error {
	ret := _m.Called(ping)

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Ping) error); ok {
		r0 = rf(ping)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
