// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import models "github.com/NodeFactoryIo/vedran/internal/models"
import repositories "github.com/NodeFactoryIo/vedran/internal/repositories"

// Actions is an autogenerated mock type for the Actions type
type Actions struct {
	mock.Mock
}

// PenalizeNode provides a mock function with given fields: node, _a1
func (_m *Actions) PenalizeNode(node models.Node, _a1 repositories.Repos) {
	_m.Called(node, _a1)
}
