// Code generated by mockery v2.2.1. DO NOT EDIT.

package mocks

import (
	models "github.com/NodeFactoryIo/vedran/internal/models"
	repositories "github.com/NodeFactoryIo/vedran/internal/repositories"
	mock "github.com/stretchr/testify/mock"
)

// Actions is an autogenerated mock type for the Actions type
type Actions struct {
	mock.Mock
}

// PenalizeNode provides a mock function with given fields: node, _a1
func (_m *Actions) PenalizeNode(node models.Node, _a1 repositories.Repos) {
	_m.Called(node, _a1)
}

// RewardNode provides a mock function with given fields: node, _a1
func (_m *Actions) RewardNode(node models.Node, _a1 repositories.Repos) {
	_m.Called(node, _a1)
}
