// Code generated by mockery v2.2.1. DO NOT EDIT.

package mocks

import (
	io "io"

	proto "github.com/NodeFactoryIo/vedran/pkg/http-tunnel/proto"
	mock "github.com/stretchr/testify/mock"
)

// ProxyFunc is an autogenerated mock type for the ProxyFunc type
type ProxyFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: w, r, msg
func (_m *ProxyFunc) Execute(w io.Writer, r io.ReadCloser, msg *proto.ControlMessage) {
	_m.Called(w, r, msg)
}
