package cmd

import (
	"errors"
	"fmt"
	"github.com/NodeFactoryIo/vedran/internal/httptunnel"
	"github.com/NodeFactoryIo/vedran/internal/ip"
	"strings"

	"github.com/NodeFactoryIo/vedran/internal/configuration"
	"github.com/NodeFactoryIo/vedran/internal/loadbalancer"
	"github.com/NodeFactoryIo/vedran/pkg/logger"
	"github.com/NodeFactoryIo/vedran/pkg/util/random"
	log "github.com/sirupsen/logrus"
	"github.com/spf13/cobra"
)

var (
	// load balancer related flags
	authSecret string
	name       string
	capacity   int64
	whitelist  []string
	fee        float32
	selection  string
	port       int32
	publicIP   string
	// logging related flags
	logLevel string
	logFile  string
	// http tunnel related flags
	tunnelServerPort string
	tunnelPortRange  string
)

var startCmd = &cobra.Command{
	Use:   "start",
	Short: "Starts vedran load balancer",
	Run:   startCommand,
	PreRunE: func(cmd *cobra.Command, args []string) error {
		level, err := log.ParseLevel(logLevel)
		if err != nil {
			log.Fatalf("Invalid log level %s", logLevel)
		}
		err = logger.SetupLogger(level, logFile)
		if err != nil {
			return err
		}
		return nil
	},
	Args: func(cmd *cobra.Command, args []string) error {
		// valid values are round-robin and random
		if selection != "round-robin" && selection != "random" {
			return errors.New("invalid selection option selected")
		}
		// all positive integers are valid, and -1 representing unlimited capacity
		if capacity < -1 {
			return errors.New("invalid capacity value")
		}
		// valid value is between 0-1
		if fee < 0 || fee > 1 {
			return errors.New("invalid fee value")
		}
		// well known ports and registered ports
		if port <= 0 && port > 49151 {
			return errors.New("invalid port number")
		}
		// valid format is PortMin:PortMax
		if prt := strings.Split(tunnelPortRange, ":"); len(prt) != 2 {
			return errors.New("invalid port range, should be defined as \"PortMin:PortMax\"")
		}
		return nil
	},
}

func init() {
	startCmd.Flags().StringVar(
		&authSecret,
		"auth-secret",
		"",
		"[REQUIRED] Authentication secret used for generating tokens")

	startCmd.Flags().StringVar(
		&name,
		"name",
		fmt.Sprintf("load-balancer-%s", random.String(12, random.Alphabetic)),
		"[OPTIONAL] Public name for load balancer, autogenerated name used if omitted")

	startCmd.Flags().Int64Var(
		&capacity,
		"capacity",
		-1,
		"[OPTIONAL] Maximum number of nodes allowed to connect, where -1 represents no upper limit")

	startCmd.Flags().StringSliceVar(
		&whitelist,
		"whitelist",
		nil,
		"[OPTIONAL] Comma separated list of node id-s, if provided only these nodes will be allowed to connect")

	startCmd.Flags().Float32Var(
		&fee,
		"fee",
		0.1,
		"[OPTIONAL] Value between 0-1 representing fee percentage")

	startCmd.Flags().StringVar(
		&selection,
		"selection",
		"round-robin",
		"[OPTIONAL] Type of selection used for choosing nodes (round-robin, random)")

	startCmd.Flags().Int32Var(
		&port,
		"port",
		4000,
		"[OPTIONAL] Port on which load balancer will be started")

	startCmd.Flags().StringVar(
		&publicIP,
		"public-ip",
		"",
		"[OPTIONAL] Public ip of load balancer")

	startCmd.Flags().StringVar(
		&logLevel,
		"log-level",
		"error",
		"[OPTIONAL] Level of logging (eg. info, warn, error)")

	startCmd.Flags().StringVar(
		&logFile,
		"log-file",
		"",
		"[OPTIONAL] Path to logfile (default stdout)")

	startCmd.Flags().StringVar(
		&tunnelServerPort,
		"tunnel-port",
		"5223",
		"[OPTIONAL] Address on which http tunnel server is running")

	startCmd.Flags().StringVar(
		&tunnelPortRange,
		"tunnel-port-range",
		"20000:30000",
		"[OPTIONAL] Range of ports which is used to open http tunnels")

	RootCmd.AddCommand(startCmd)
}

func startCommand(_ *cobra.Command, _ []string) {
	DisplayBanner()

	var tunnelURL string
	if publicIP == "" {
		IP, err := ip.Get()
		if err != nil {
			log.Error("Unable to fetch public IP ", err)
			return
		}
		tunnelURL = fmt.Sprintf("%s:%s", IP.String(), tunnelServerPort)
		log.Infof("HTTP tunnel will be started on %s with port range %s", tunnelURL, tunnelPortRange)
	}

	httptunnel.StartHttpTunnelServer(tunnelServerPort, tunnelPortRange)

	loadbalancer.StartLoadBalancerServer(configuration.Configuration{
		AuthSecret: authSecret,
		Name:       name,
		Capacity:   capacity,
		Whitelist:  whitelist,
		Fee:        fee,
		Selection:  selection,
		Port:       port,
		TunnelURL:  tunnelURL,
	})
}
