global:
  scrape_interval:     15s
  evaluation_interval: 15s

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['vedran:4000']
